version: 0.2

env:
  variables:
    environment: "dev"
phases:
  install:
    commands:
      - sudo yum install python3.7
      - python3 --version
      - python3 -m ensurepip --upgrade
      - python3 -m pip install --upgrade pip
      - python3 -m pip install --upgrade virtualenv
      - python3 -m pip install -r requirements.txt
  prebuild:
    commands:
      - cdk synth
  build:
    commands:
      - printenv